config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: 'admins'
  devise_for :employees, path: 'employees'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index create]

  namespace :admins do
    resources :kudos
    resources :company_values
    resources :rewards
    resources :categories
    resources :employees do
      get 'kudos_for_all', on: :collection
      patch 'update_kudos_for_all', on: :collection
    end
    resources :orders, only: %i[index]
    resource :orders do
      get 'export'
      patch 'change_status'
    end
    root to: 'pages#home'
  end

  root to: 'pages#home'
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :given_kudos, class_name: 'Kudo', foreign_key: :giver, dependent: :destroy, inverse_of: :giver
  has_many :received_kudos, class_name: 'Kudo', foreign_key: :receiver, dependent: :destroy, inverse_of: :receiver
  has_many :orders, dependent: :destroy
  has_many :bought_rewards, through: :orders, source: :reward

  def earned_points
    received_kudos.count - bought_rewards.sum(:price).to_i
  end
end

app/controllers/admins/employees_controller.rb
# frozen_string_literal: true

module Admins
  class EmployeesController < Admins::BaseController
    def index
      render :index, locals: { employees: Employee.all }
    end

    def show
      render :show, locals: { employee: employee }
    end

    def edit
      render :edit, locals: { employee: employee }
    end

    def update
      if employee.update(employee_params)
        redirect_to admins_employee_path(employee), info: 'Employee was successfully updated.'
      else
        render :edit, locals: { employee: employee }
      end
    end

    def destroy
      employee.destroy
      redirect_to admins_employees_path, danger: 'Employee was successfully destroyed.'
    end

    def kudos_for_all
      render :update_kudos_for_all, locals: { employees: Employee.all }
    end

    def update_kudos_for_all
      Employee.transaction do
        Employee.all.each do |e|
          kudos = params[:employee][:additional_kudos].to_i
          e.number_of_available_kudos += kudos
          e.save!
        end
        redirect_to admins_employees_path, info: 'Employee was successfully updated.'
      end
    rescue StandardError
      render :kudos_for_all, danger: 'Try again sth went wrong'
    end

    private

    def employee
      @employee ||= Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:email, :number_of_available_kudos)
    end
  end
end

app/views/admins/employees/_form.html.erb
<%= form_with(model: [:admins, employee ]) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/employees/edit.html.erb
<h1>Editing Admins Employee</h1>

<%= render 'form', employee: employee %>

<%= link_to 'Back', admins_employees_path %>

app/views/admins/employees/index.html.erb
<h1>Admin Panel: Employees</h1>

<%= link_to 'Add kudos', kudos_for_all_admins_employees_path %></td>
<table class="table table-success table-striped">
  <thead>
    <tr>
      <th>Available kudos</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% employees.each do |employee| %>
      <tr>
        <td class="table-primary"><%= employee.number_of_available_kudos %></td>
        <td class="table-primary"><%= link_to employee.email , admins_employee_path(employee) %></td>
        <td class="table-primary"><%= link_to "Edit this Employee", edit_admins_employee_path(employee) %>
        <%= link_to 'Destroy this employee', admins_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/employees/show.html.erb
Employee:
<p> Email: <%= employee.email %> </p>

<%= link_to 'Edit', edit_admins_employee_path(employee) %> |
<%= link_to 'Back', admins_employees_path %>

app/views/admins/employees/update_kudos_for_all.html.erb
<%= form_for :employee, url: update_kudos_for_all_admins_employees_path, method: :patch do |form| %>
  <%= form.label :additional_kudos, "Additional kudos for all employees:" %>
  <%= form.number_field :additional_kudos, in: 1.0..20.0, step: 1.0 %>
  <%= form.submit "Submit" %>
<% end %>