config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: 'admins'
  devise_for :employees, path: 'employees'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index create]

  namespace :admins do
    resources :kudos
    resources :company_values
    resources :rewards
    resources :categories
    resources :employees do
      get 'kudos_for_all', on: :collection
      patch 'update_kudos_for_all', on: :collection
    end
    resources :orders, only: %i[index]
    resource :orders do
      get 'export'
      patch 'change_status'
    end
    root to: 'pages#home'
  end

  root to: 'pages#home'
end

app/views/admins/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container">
    <a class="navbar-brand" href="/">Employee Recognition Platform</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", admins_root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Kudos", admins_kudos_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Company Values", admins_company_values_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Rewards", admins_rewards_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Employees", admins_employees_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Orders", admins_orders_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Rewards Categories", admins_categories_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
    <div class="right-part-navbar">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-secondary btn-inverse'%>
        <% else %>
          <%= link_to "Sign in", new_admin_registration_path, class: 'nav-link btn btn-outline-secondary btn-inverse'%> 
          <%= link_to "Log in", admin_session_path, class: 'nav-link btn btn-outline-secondary btn-inverse'%>
        <% end %>
        <%= link_to "Admin Panel", admins_root_path, class: 'nav-link btn btn-outline-secondary btn-inverse'%>      </ul>
      </ul>
    </div>
  </div>
</nav>

app/views/admins/pages/home.html.erb
<div class="container">
  Hello Admin!!! 
</div>