config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: 'admins'
  devise_for :employees, path: 'employees'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index create]

  namespace :admins do
    resources :kudos
    resources :company_values
    resources :rewards
    resources :categories
    resources :employees do
      get 'kudos_for_all', on: :collection
      patch 'update_kudos_for_all', on: :collection
    end
    resources :orders, only: %i[index]
    resource :orders do
      get 'export'
      patch 'change_status'
    end
    root to: 'pages#home'
  end

  root to: 'pages#home'
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  has_many :category_rewards, dependent: :destroy
  has_many :categories, through: :category_rewards, dependent: :destroy
  has_one_attached :image

  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validate :correct_image_type

  scope :paginate, lambda { |page:, per_page: 10|
    page = (page || 1).to_i
    per_page = per_page.to_i

    current_scope = limit(per_page).offset(per_page * (page - 1))

    PaginationResult.new(current_scope).tap do |result|
      result.current_page = page
      result.total_pages = (count / per_page.to_f).ceil
    end
  }

  class PaginationResult < SimpleDelegator
    attr_accessor :current_page, :total_pages
  end

  def reward_purchasable?(employee)
    employee.earned_points >= price
  end

  def attributes
    { 'title' => nil, 'description' => nil, 'price' => nil }
  end

  private

  def correct_image_type
    return unless image.attached? && !image.content_type.in?(%w[image/jpg image/jpeg image/png])

    errors.add(:image, 'Must be a jpg or a png file')
  end
end

app/controllers/admins/rewards_controller.rb
# frozen_string_literal: true

module Admins
  class RewardsController < Admins::BaseController
    def index
      render :index, locals: { rewards: Reward.includes(:categories).all }
    end

    def show
      render :show, locals: { reward: reward }
    end

    def new
      render :new, locals: { reward: Reward.new }
    end

    def edit
      render :edit, locals: { reward: reward }
    end

    def create
      new_reward = Reward.new(reward_params)

      if new_reward.save
        redirect_to admins_rewards_path, notice: 'New Reward was successfully created.'
      else
        render :new, locals: { reward: new_reward }
      end
    end

    def update
      if reward.update(reward_params)
        redirect_to admins_reward_path(reward), notice: 'Reward was successfully updated.'
      else
        render :edit, locals: { reward: reward  }
      end
    end

    def destroy
      reward.destroy
      redirect_to admins_rewards_path, notice: 'Reward was successfully destroyed.'
    end

    private

    def reward
      @reward ||= Reward.find(params[:id])
    end

    def reward_params
      params.require(:reward).permit(:title, :description, :price, :image, category_ids: [])
    end
  end
end

app/controllers/rewards_controller.rb
# frozen_string_literal: true

class RewardsController < ApplicationController
  def index
    rewards = Reward.all
    if params[:category_id].present?
      rewards = rewards.joins(:category_rewards).where(category_rewards: { category_id: params[:category_id] })
    end
    rewards = rewards.paginate(page: params[:page], per_page: 10)
    render :index, locals: { rewards: rewards }
  end

  def show
    render :show, locals: { reward: reward }
  end

  private

  def reward
    @reward ||= Reward.find(params[:id])
  end

  def reward_params
    params.require(:reward).permit(:title, :description, :price)
  end
end

app/views/rewards/index.html.erb
<h1>Rewards</h1>

<table class="table table-success table-striped">
  <thead>
      <div class="btn-group btns">
      <% Category.all.each do |category| %>
        <%= link_to category.title, rewards_path(category_id: category.id), class: 'btn btn-info' %>
      <% end %>
      <%= link_to "All", rewards_path, class: 'btn btn-info' %>
    </div>

    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% rewards.each do |reward| %>
      <tr>
        <td class="table-primary"><%= link_to reward.title, reward_path(reward) %></td>
        <td class="table-primary"><%= reward.description %></td>
        <td class="table-primary"><%= reward.price %></td>
        <td class="table-primary"><%= reward.categories.map(&:title).join(", ") %></td>
        <td class="table-primary">
          <%= button_to "Order this reward", orders_path, params: { order: { reward_id: reward.id } }, method: :post, disabled: !reward.reward_purchasable?(current_employee) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate rewards %>

app/views/rewards/show.html.erb
Reward:
<p> Title: <%= reward.title %> </p>
<p> Title: <%= reward.description %> </p>
<p> Title: <%= reward.price %> </p>
<p> Image: 
  <% if reward.image.attached? %> 
    <%= image_tag reward.image, style: 'height:25%; width:25%' %>
  <% end %></p>


<%= link_to 'Back', rewards_path %>