config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: 'admins'
  devise_for :employees, path: 'employees'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index create]

  namespace :admins do
    resources :kudos
    resources :company_values
    resources :rewards
    resources :categories
    resources :employees do
      get 'kudos_for_all', on: :collection
      patch 'update_kudos_for_all', on: :collection
    end
    resources :orders, only: %i[index]
    resource :orders do
      get 'export'
      patch 'change_status'
    end
    root to: 'pages#home'
  end

  root to: 'pages#home'
end

app/models/kudo.rb
# frozen_string_literal: true

class Kudo < ApplicationRecord
  belongs_to :receiver, class_name: 'Employee'
  belongs_to :giver, class_name: 'Employee'
  belongs_to :company_value, class_name: 'CompanyValue'

  validate :giver_available_kudos, on: :create

  private

  def giver_available_kudos
    errors.add(:base, 'You cant give more kudos') if giver.number_of_available_kudos <= 0
  end
end

app/controllers/admins/kudos_controller.rb
# frozen_string_literal: true

module Admins
  class KudosController < Admins::BaseController
    def index
      render :index, locals: { kudos: Kudo.includes(:giver, :receiver, :company_value).all }
    end

    def show
      render :show, locals: { kudo: kudo, presenter: KudoPresenter.new }
    end

    def new
      render :new, locals: { kudo: Kudo.new, presenter: KudoPresenter.new }
    end

    def edit
      render :edit, locals: { kudo: kudo, presenter: KudoPresenter.new }
    end

    def create
      record = Kudo.new(kudo_params)

      if record.save
        redirect_to admins_kudos_path, notice: 'Kudo was successfully created.'
      else
        render :new, locals: { kudo: record, presenter: KudoPresenter.new }
      end
    end

    def update
      if kudo.update(kudo_params)
        redirect_to admins_kudo_path(kudo), notice: 'Kudo was successfully updated.'
      else
        render :edit, locals: { kudo: kudo, presenter: KudoPresenter.new }
      end
    end

    def destroy
      kudo.destroy
      redirect_to admins_kudos_path, notice: 'Kudo was successfully destroyed.'
    end

    private

    def kudo
      @kudo ||= Kudo.find(params[:id])
    end

    def kudo_params
      params.require(:kudo).permit(:content, :title, :receiver_id, :giver_id, :company_value_id)
    end
  end
end

app/controllers/kudos_controller.rb
# frozen_string_literal: true

class KudosController < ApplicationController
  before_action :authenticate_employee!

  def index
    render :index, locals: { kudos: Kudo.includes(:giver, :receiver, :company_value).all }
  end

  def new
    render :new, locals: { kudo: Kudo.new, presenter: KudoPresenter.new }
  end

  def show
    render :show, locals: { kudo: kudo, presenter: KudoPresenter.new }
  end

  def create
    record = Kudo.new(kudo_params)
    record.giver = current_employee

    if record.save
      employee_kudos = current_employee.number_of_available_kudos
      current_employee.number_of_available_kudos = employee_kudos - 1
      current_employee.save!
      redirect_to kudos_path, notice: 'Kudo was successfully created.'
    else
      render :new, locals: { kudo: record, presenter: KudoPresenter.new }
    end
  end

  def update
    raise danger: 'You cannot edit/destroy this kudo after 5 minutes!' unless authorize kudo

    if kudo.update(kudo_params)
      redirect_to kudo_path(kudo), notice: 'Kudo was successfully updated.'
    else
      render :edit, locals: { kudo: kudo, presenter: KudoPresenter.new }
    end
  end

  def edit
    render :edit, locals: { kudo: kudo, presenter: KudoPresenter.new }
  end

  def destroy
    kudo.destroy
    redirect_to kudos_path, notice: 'Kudo was successfully destroyed.'
  end

  private

  def kudo_params
    params.require(:kudo).permit(:content, :title, :receiver_id, :company_value_id)
  end

  def kudo
    @kudo ||= Kudo.find(params[:id])
  end
end

app/helpers/admins/kudos_helper.rb
# frozen_string_literal: true

module Admins
  module KudosHelper
  end
end

app/views/kudos/_form.html.erb
<%= form_with model: kudo do |form| %>
<% if kudo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(kudo.errors.count, "error") %> prohibited this kudo value from being saved:</h2>

    <ul>
      <% kudo.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.collection_select :receiver_id, presenter.employees_for_select, :id, :email %>
  </div>

  <div class="field">
    <%= form.label :company_value_id %>
    <%= form.collection_select :company_value_id, presenter.company_values_for_select, :id, :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kudos/edit.html.erb
<h1>Edit kudo:</h1>

<%= render 'form', kudo: kudo, presenter: presenter %>

app/views/kudos/index.html.erb
<h1>Kudos</h1>

<table class="table table-success table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Giver</th>
      <th>Receiver</th>
      <th>Created at</th>
      <th>Company Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% kudos.each do |kudo| %>
      <tr>
        <td class="table-primary"><%= kudo.title %></td>
        <td class="table-primary"><%= kudo.content %></td>
        <td class="table-primary"><%= kudo.giver.email %></td>
        <td class="table-primary"><%= kudo.receiver.email %></td>
        <td class="table-primary"><%= kudo.created_at %></td>
        <td class="table-primary"><%= kudo.company_value.title %></td>
        <td class="table-primary">
          <% if policy(kudo).update? %>
            <%= link_to "Edit this Kudo", edit_kudo_path(kudo) %>
            <%= link_to 'Destroy this kudo', kudo, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Create New Kudo", new_kudo_path %>

app/views/kudos/new.html.erb
<h1>New Kudo Form</h1>

<%= render 'form', kudo: kudo, presenter: presenter %>

app/views/kudos/show.html.erb
<p>
  <strong>Title:</strong>
  <%= kudo.title %>

  <p> Content: <%= kudo.content %> </p>
  <p> Giver: <%= kudo.giver.email %> </p>
  <p> Receiver: <%= kudo.receiver.email %> </p>
  <p> Created at: <%= kudo.created_at %> </p>
  <p>Company Value: <%= kudo.company_value.title %>
</p>